ifndef::imagesdir[:imagesdir: images]

[.text-left]
=== Regulated and Self-contained eESPD

This new version of the eESPD makes the difference between “Regulated” and “Self-contained” eESPD. 

Regulated eESPDs are those XML document instances the structure and content of which are strictily adjusted to the terms expressed in the Annex 2 of the Commission Implementing Regulation (EU) 2016/7 (1): Standard form for the European Single Procurement document (ESPD). Hence a Regulated eESPD will refer to documents and information that is external, e.g. mentioned in the Contract Notice published or the Contract Documents.

In a Self-contained eESPD the definition of the criteria, its properties and requirements that are particular to the MS or to the Contracting Authority, and both generic to all Procurement Procedures or particular of the Procurement Procedure, are explicitly mentioned or defined in the eESPD document. Self-contained eESPDs confer the Contracting Authorities a greater flexibility when preparing their eESPD Request documents. 