ifndef::imagesdir[:imagesdir: images]

[.text-left]
=== Technical notes

For the migration towards the new ESDP-EDM 2.0.0, the software developers need to take into considerations these technical aspects:  

*  The data architecture model used in previous versions is not used anymore. UBL-2.2  uses its own. Therefore:

**  The ccv: and cev: prefixes (and corresponding namespaces)  are not used in ESPD-2.0.0. Instead, UBL-2.2 compiles all the Common Basic Components in one single library and uses the prefix “cbc:”;

**  UBL-2.2 distributes two sets of XSD schema: see folders “xsd” and “xsdrt” of the UBL distribution package. The “xsd” folder contains the schemata fully documented (with dictionary entry names, definitions, examples, etc.); whilst the “xsdrt” schemata are not likewise documented and are frequently used in production environments (“rt” stands for “run-time”);

*  UBL-2.2 defines thousands of different information components and dozens of documents. The ESPD-EDM reuses only a small set of those components and only 2 documents. This document describes and illustrates only those elements from UBL-2.2 that are actually used by the eESPD. For details on the rest of unused UBL-2.2 elements see the spread-sheet /dist/mod/UBL-Entities-2.2-Pre-award.xls.xlsx. 

*  The documents ESDPRequest and ESPDResponse, from the previous versions of the ESPD-EDM, are named in UBL-2.2: QualificationApplicationRequest and QualificationApplicationResponse. The new ESPD-EDM-2.0.0 uses these documents as they are offered and named by UBL-2.2.

*  The elements Criterion, Response and Evidence from the previous version 1.0.2 of the ESPD-EDM behave are differently named and designed in UBL-2.0.0.;

*  The responses to a particular question and the evidences are now directly associated to the root element of the Response document.

*  In order to align all the semantic artefacts that accompany the new ESPD-EDM version 2.0.0, all the lists maintained by EU-COM-GROW have been versioned also as “2.0.0”. This includes the new Code Lists and Criteria Taxonomy as well as the previous ones even if the content of the list has not suffered any change. See “6.1 Code Lists” for more details on the Code Lists.